BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Estudante (
id INTEGER PRIMARY KEY,
matricula INTEGER,
nome TEXT
);
INSERT INTO "Estudante" VALUES (1,200520152025,'Ítalo Robert Pereira Amaro');
COMMIT;
